{{ if .Values.grafana.enabled -}}
{{ if .Values.grafana.timescale.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-db
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{ if .Values.timescaledbExternal.enabled }}
  GF_DATABASE_HOST: {{ include "tobs.dburi.host" . | b64enc }}
{{ else }}
  {{- $host := tpl .Values.grafana.timescale.database.host $ -}}
  {{- $port := .Values.grafana.timescale.database.port | int -}}
  {{- $fullhost := printf "%s:%d" $host $port }}
  GF_DATABASE_HOST: {{ $fullhost | b64enc }}
{{ end }}
  GF_DATABASE_TYPE: {{ "postgres" | b64enc }}
  GF_DATABASE_NAME: {{ ternary (include "tobs.dburi.dbname" . | b64enc) (.Values.grafana.timescale.database.dbName | b64enc) (.Values.timescaledbExternal.enabled) }}
  GF_DATABASE_USER: {{ ternary (include "tobs.dburi.user" . | b64enc) (.Values.grafana.timescale.database.user | b64enc) (.Values.timescaledbExternal.enabled) }}
  GF_DATABASE_PASSWORD: {{ ternary (include "tobs.dburi.password" . | b64enc) (.Values.grafana.timescale.database.pass | b64enc) (.Values.timescaledbExternal.enabled) }}
  GF_DATABASE_SSL_MODE: {{ ternary (include "tobs.dburi.sslmode" . | b64enc) (.Values.grafana.timescale.database.sslMode | b64enc) (.Values.timescaledbExternal.enabled) }}
{{- end -}}
{{- end -}}