name: Static deploy generation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./cli
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out master
        uses: actions/checkout@v2

      - name: Test static generation
        run: |
          ./generate-deploy-script.sh
          # git diff --exit-code

      - name: Format
        working-directory: ${{env.working-directory}}
        run: |
          make go-fmt

      - name: Vet
        working-directory: ${{env.working-directory}}
        run: |
          make go-vet

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
          golangci-lint run

      - name: Build
        working-directory: ${{env.working-directory}}
        run: |
          make build

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
      - name: Tests
        working-directory: ${{env.working-directory}}
        run: |
          make test
